### ISSUE TITLE
Waypoint config may occasionally fail to generate, causing clients to crash when opening the map

### ISSUE THREAD

**Issue by CringeAura** [Wynntils/Wynntils-Legacy#111]
See ticket 0154 for more details

**Comment by MitalAshok** [comment]
This has been fixed. The issue was in older versions, the waypoints were stored differently (Just one type, `MARKER`, which doesn't exist anymore), so it crashed because the type of the waypoint was set to null. Fixed by this: https://github.com/Wynntils/Wynntils/commit/22814f29b650617a1a8fa2d682240b08746309ef#diff-06b8a462b4c68392d730dc2190f72fdcR56
