### ISSUE TITLE
Nullpointerexception crash when loading data from API 

### ISSUE THREAD

**Issue by mount2010** [Wynntils/Wynntils-Legacy#130]
Wynntils is crashing when it loads data from the API due to a null pointer exception. I've provided the crash report below. I initially had Foamfix and Wynncraft Rich Presence, but I disabled them to try to solve the issue.

OS: Ubuntu 18.04 LTS 64 bit

[crash-2019-08-06_19.54.25-client.txt](https://github.com/Wynntils/Wynntils/files/3472067/crash-2019-08-06_19.54.25-client.txt)

**Comment by HighCrit** [comment]
This issue has been fixed in the latest development build.

The Wynncraft territory API takes too long to load - which may cause a crash on startup. To fix this you'll have to download the latest Cutting Edge build from: https://ci.wynntils.com/job/Wynntils-DEV/lastSuccessfulBuild/ and put it in your mods folder (delete the old version). 

Then start-up Minecraft and click Mods>Wynntils>Config>Core and change STABLE to CUTTING_EDGE (under download stream).

[Image Guide](https://cdn.discordapp.com/attachments/424990647309697026/608230676587872256/Naamloos.png)
DO NOT FORGET TO HIT APPLY

**Comment by mount2010** [comment]
Thanks for the speedy reply.

Minecraft now launches and works.
