### ISSUE TITLE
Using the reload button and "/wynntils debug" does not fix the quest book not showing quests

### ISSUE THREAD

**Issue by CringeAura** [Wynntils/Wynntils-Legacy#142]

**Comment by MitalAshok** [comment]
Issues:

1. Item slot not being changed.
2. If the packet queue can't verify the packet, and the right click is resent, it's filtered out (by the "Open Wynntils questbook instead of default quest book" mechanism) because only the next (1) right click is ignored after a FakeInventory is opened.

Fixes:

1. Queue change inventory slot at the same time as the right click to open the quest book. This way if the verification does not pass, the slot change will be sent again too. https://github.com/Wynntils/Wynntils/commit/968d254990b6cf762fd3da69c9237041acd175db#diff-764f8dbca7e5e558bd1270b86e4093adR109-R112
2. All right clicks sent by FakeInventory are now not filtered. https://github.com/Wynntils/Wynntils/commit/ce8b1ea975dad46980e08457b00d93bb2437a5df#diff-5025aba04ca5e8d34d75a7b9395b6da2R32-R35

These were the main issues for me before, and the reload button works now. If there aren't any more problems, we should be able to close this issue.

Also another issue I fixed was where if the window wasn't opened, the FakeInventory event handler was still registered untill the next window opened was fixed (Unregistering it [here](https://github.com/Wynntils/Wynntils/commit/968d254990b6cf762fd3da69c9237041acd175db#diff-764f8dbca7e5e558bd1270b86e4093adR113-R120) if the queue drops the packets)
