### ISSUE TITLE
Blue Circle/Health and mana showing zero

### ISSUE THREAD

**Issue by KillerApple** [Wynntils/Wynntils-Legacy#674]
### Version

wynntils-0.0.2-alpha.470-fabric

### Brief Description

Ever time I cast a spell a blue circle covering 90% of screen pops up.
The health and mana showing zero was after I closed the game now they don't track in general.

### Steps to Reproduce

IDK

### Expected Behaviour

IDK

### Actual Behaviour

IDK

### Installed Mods

BetterF3
Forge Config API Port [Fabric]
Iceberg [Fabric]
Iris Shaders
Legendary Tooltips [Fabric]
Lithium (Fabric)
Logical Zoom
Mod Menu
Prism [Fabric]
Reese's Sodium Options
Sodium
Sodium Extra
Visuality

**Comment by kristofbolyai** [comment]
1, This is the 1.12.2 repository. https://github.com/Wynntils/Artemis is the correct one.
2, Instead of creating a Github issue without basically providing any info, you are better off asking the community. Neither of the 2 issues are actually a bug, the first one is a feature, second one is most likely you changing some settings in-game.
