### ISSUE TITLE
dialogue keeps repeating

### ISSUE THREAD

**Issue by Buttsaggington69** [Wynntils/Wynntils-Legacy#685]
### Version

v0.0.3-alpha.304

### Brief Description

when i get into a dialougue the musik sort of skips voices of wynn repeats the first few words of the dialogue and my refreshes on the right side keep stacking even if i havent cast a spell

### Steps to Reproduce

get into dialogue

### Expected Behaviour

dialogue plays like normal and no extra skill refresh notifications

### Actual Behaviour

repeating first few words of dialogue in voices of wynn, stacking skill refresh notifications, that dont stop until after leaving dialogue

### Additional Comments

im not sure why this happens ive just installed the mods with the [wynntils] mod installer

### Installed Mods

i used the wynntills mod installer so nothing that didnt come with that

**Comment by the-wright-jamie** [comment]
This is the wrong repository for this.

The Voices of Wynn Team have released a patch which appears to be available here: https://voicesofwynn.com/downloads/46

**Comment by kristofbolyai** [comment]
Indeed it is. Thank you for clearing it up. Also note that this repository is for 1.12.2 version of the mod. https://github.com/Wynntils/Artemis would be the 1.19.4 version.

**Comment by the-wright-jamie** [comment]
@kristofbolyai probably not the right place for this but would you/someone on the team consider putting a deprecation + redirect notice at the top of the ReadMe and archive the project so that new issues can no longer be created?

I just found out about Wynntils so it's not my place to say as I don't know the current status of both projects but I do consider it good open-source etiquette to clearly mark when projects are deprecated and/or moved repository. Complete randomer's opinion though, feel free to disregard it 🙃

**Comment by kristofbolyai** [comment]
We are currently in the process of sunsetting this version/repo. Once we are fully done with migrating, we will make sure to officially sunset this repo as well.

**Comment by the-wright-jamie** [comment]
Grand, good to know! Keep up the awesome work, I really appreciate Wynntils! Super cool project.
